name: Build

on: [push]

env:
  CIBW_SKIP: pp*
  CIBW_BEFORE_BUILD: python -m pip install cmake && git submodule update --init --recursive
  CIBW_TEST_COMMAND: python -m pip install scipy && python {project}/test.py
  MACOSX_DEPLOYMENT_TARGET: "10.14"
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
    - uses: actions/checkout@v2

    - name: Check cmake
      run: cmake --version

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.8'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.2.2
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir dist
    - name: Look
      run: |
        ls dist
    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist

  build_source:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.8'
    
    - name: Build source
      run: |
        git submodule update --init --recursive
        python -m pip install setuptools
        python setup.py sdist --formats=zip
    - name: Look
      run: |
        ls dist
    
    - name: Test install
      run: |
        cd dist
        python -m venv env
        source env/bin/activate
        python -m pip install *.zip
        python -m pip install scipy
        python ../test.py
        cd ..

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist
  
  test_source:
    runs-on: ubuntu-20.04
    needs: [build_source]

    steps:
    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.8'

    - uses: actions/download-artifact@v2
      with:
        name: wheels
        path: ./dist
  
  upload:
    runs-on: ubuntu-20.04
    needs: [test_source, build_wheels]
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: wheels
        path: ./dist
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      continue-on-error: true
      with:
        password: ${{ secrets.testpypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}