name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Check cmake
      run: cmake --version

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0
    - name: Install Visual C++ for Python 3.7
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install vcpython37 -f -y
    - name: Build wheel
      run: |
        python -m pip install numpy scipy
        python -m cibuildwheel --output-dir wheelhouse
    - name: Look
      run: |
        ls wheelhouse
    - name: Test
      run: |
        python ./test.py
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
