name: Build

on: [push, pull_request]

env:
  CIBW_SKIP: cp34-* cp35-* *-manylinux_i686 *-win32
  CIBW_BUILD: cp3?-*
  CIBW_BEFORE_BUILD: python -m pip install cmake numpy scipy && git submodule update --init
  CIBW_TEST_COMMAND: python {project}/test.py

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest] # ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Check cmake
      run: cmake --version

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - name: Look
      run: |
        ls wheelhouse
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
